### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by kctess5** [hosang/gdt#1]
Please consider adding a license to make it clear how your work can be used by others. I would like to be explore making an open source derivative work, so an open source license like the MIT license would be much appreciated.

Cheers!

**Comment by hosang** [comment]
Happy somebody fonds this useful! 

I have to check which licenses are okay, since I don't remember how close it is to Pedro's code. I'd be happy to put it under MIT. 

Feel free to ping me again if I forget to take care of it.

**Comment by hosang** [comment]
I finally added a license. Let me know if you end up using it!
